// ─────────────────────────────────────────────────────────────────────────────
// Mock tourism data — Saudi attractions + hotels / furnished apartments
// ─────────────────────────────────────────────────────────────────────────────

export type AttractionCategory = "landmark" | "entertainment" | "restaurant" | "shopping";

export interface Attraction {
  id: string;
  nameAr: string;
  nameEn: string;
  city: string;
  cityEn: string;
  category: AttractionCategory;
  rating: number;
  reviewCount: number;
  emoji: string;
  descAr: string;
  descEn: string;
  image: string;
}

export interface HotelListing {
  id: string;
  nameAr: string;
  nameEn: string;
  city: string;
  cityEn: string;
  district: string;
  districtEn: string;
  type: "hotel" | "furnished_apt" | "resort";
  stars: number;
  pricePerNight: number;
  image: string;
  rating: number;
  reviewCount: number;
  phone: string;
  amenitiesAr: string[];
  amenitiesEn: string[];
  descAr: string;
  descEn: string;
  lat: number;
  lng: number;
}

export const ATTRACTIONS: Attraction[] = [
  {
    id: "a1",
    nameAr: "الدرعية التاريخية",
    nameEn: "Historic Diriyah",
    city: "الرياض", cityEn: "Riyadh",
    category: "landmark", rating: 4.9, reviewCount: 12500, emoji: "🏛️",
    image: "https://images.unsplash.com/photo-1578662996442-48f60103fc96?w=800",
    descAr: "مدينة الدرعية التاريخية، مهد الدولة السعودية الأولى وأحد أبرز المواقع التراثية في العالم.",
    descEn: "The birthplace of the first Saudi state and one of the world's most prominent heritage sites.",
  },
  {
    id: "a2",
    nameAr: "العُلا — الحِجر",
    nameEn: "AlUla — Hegra",
    city: "العُلا", cityEn: "AlUla",
    category: "landmark", rating: 4.9, reviewCount: 8900, emoji: "🗿",
    image: "https://images.unsplash.com/photo-1591017403521-0d3c6e09f24e?w=800",
    descAr: "وجهة سياحية استثنائية تضم أقدم المواقع الأثرية بشبه الجزيرة العربية، بما فيها الحِجر.",
    descEn: "An exceptional destination featuring the Arabian Peninsula's oldest archaeological sites, including Hegra.",
  },
  {
    id: "a3",
    nameAr: "بوليفارد الرياض",
    nameEn: "Boulevard Riyadh",
    city: "الرياض", cityEn: "Riyadh",
    category: "entertainment", rating: 4.7, reviewCount: 34000, emoji: "🎡",
    image: "https://images.unsplash.com/photo-1514890547357-a9ee288728e0?w=800",
    descAr: "مدينة ترفيهية متكاملة تضم أكثر من 100 وجهة ترفيهية وتجارية وفعاليات يومية متنوعة.",
    descEn: "A full-scale entertainment city with over 100 dining, retail, and entertainment destinations.",
  },
  {
    id: "a4",
    nameAr: "كورنيش جدة",
    nameEn: "Jeddah Corniche",
    city: "جدة", cityEn: "Jeddah",
    category: "landmark", rating: 4.6, reviewCount: 22000, emoji: "🌊",
    image: "https://images.unsplash.com/photo-1565541962553-5c1dae0d5e83?w=800",
    descAr: "واجهة بحرية ممتدة على 30 كيلومتراً تطل على البحر الأحمر، مثالية للنزهات.",
    descEn: "A 30-kilometer seafront promenade along the Red Sea, perfect for walks and leisure.",
  },
  {
    id: "a5",
    nameAr: "نيوم",
    nameEn: "NEOM",
    city: "تبوك", cityEn: "Tabuk",
    category: "landmark", rating: 4.8, reviewCount: 5200, emoji: "🌆",
    image: "https://images.unsplash.com/photo-1486325212027-8081e485255e?w=800",
    descAr: "مدينة المستقبل على ساحل البحر الأحمر، مشروع رؤية 2030 الطموح.",
    descEn: "The city of the future on the Red Sea coast, Saudi Vision 2030's ambitious megaproject.",
  },
  {
    id: "a6",
    nameAr: "قرية الحجاز",
    nameEn: "Al-Hijaz Village",
    city: "جدة", cityEn: "Jeddah",
    category: "restaurant", rating: 4.5, reviewCount: 9800, emoji: "🍽️",
    image: "https://images.unsplash.com/photo-1555396273-367ea4eb4db5?w=800",
    descAr: "قرية تراثية تجمع أشهى المطاعم الحجازية الأصيلة في أجواء تراثية فريدة.",
    descEn: "A heritage village gathering the finest authentic Hijazi restaurants in a unique traditional setting.",
  },
  {
    id: "a7",
    nameAr: "مول الرياض",
    nameEn: "Riyadh Mall",
    city: "الرياض", cityEn: "Riyadh",
    category: "shopping", rating: 4.3, reviewCount: 18000, emoji: "🛍️",
    image: "https://images.unsplash.com/photo-1567449303183-ae0d6ed1498e?w=800",
    descAr: "أحد أبرز مراكز التسوق في الرياض مع أكثر من 400 متجر وخيارات ترفيه متعددة.",
    descEn: "One of Riyadh's premier shopping destinations with over 400 stores.",
  },
  {
    id: "a8",
    nameAr: "حديقة الملك فهد",
    nameEn: "King Fahd Park",
    city: "الدمام", cityEn: "Dammam",
    category: "entertainment", rating: 4.4, reviewCount: 7600, emoji: "🌳",
    image: "https://images.unsplash.com/photo-1441974231531-c6227db76b6e?w=800",
    descAr: "أكبر حديقة عامة في المنطقة الشرقية مع مناطق ألعاب ومسارات للمشي.",
    descEn: "The largest public park in the Eastern Province with playgrounds and walking trails.",
  },
  {
    id: "a9",
    nameAr: "المسجد الحرام",
    nameEn: "Al-Masjid Al-Haram",
    city: "مكة المكرمة", cityEn: "Makkah",
    category: "landmark", rating: 5.0, reviewCount: 150000, emoji: "🕋",
    image: "https://images.unsplash.com/photo-1565534887628-fc54cdf7bf3d?w=800",
    descAr: "المسجد الحرام بمكة المكرمة، أقدس مكان في الإسلام ومقصد ملايين المسلمين.",
    descEn: "Al-Masjid Al-Haram in Makkah, the holiest site in Islam.",
  },
  {
    id: "a10",
    nameAr: "المسجد النبوي",
    nameEn: "Al-Masjid An-Nabawi",
    city: "المدينة المنورة", cityEn: "Madinah",
    category: "landmark", rating: 5.0, reviewCount: 120000, emoji: "🕌",
    image: "https://images.unsplash.com/photo-1591604129939-f1efa4d9f7fa?w=800",
    descAr: "المسجد النبوي الشريف في المدينة المنورة، ثاني أقدس المساجد في الإسلام.",
    descEn: "The Prophet's Mosque in Madinah, the second holiest mosque in Islam.",
  },
  {
    id: "a11",
    nameAr: "موسم الرياض",
    nameEn: "Riyadh Season",
    city: "الرياض", cityEn: "Riyadh",
    category: "entertainment", rating: 4.6, reviewCount: 28000, emoji: "🎭",
    image: "https://images.unsplash.com/photo-1492684223066-81342ee5ff30?w=800",
    descAr: "موسم الرياض، أكبر حدث ترفيهي في المملكة يجمع أشهر الفنانين والعروض العالمية.",
    descEn: "Riyadh Season, the Kingdom's largest entertainment event.",
  },
  {
    id: "a12",
    nameAr: "متحف المملكة",
    nameEn: "Museum of the Kingdom",
    city: "الرياض", cityEn: "Riyadh",
    category: "landmark", rating: 4.5, reviewCount: 11000, emoji: "🏛️",
    image: "https://images.unsplash.com/photo-1566127992631-137a642a90f4?w=800",
    descAr: "متحف يوثّق تاريخ المملكة العربية السعودية من العصور الحجرية حتى اليوم.",
    descEn: "A museum documenting Saudi Arabia's history from the Stone Age to the present.",
  },
  {
    id: "a13",
    nameAr: "واجهة جدة البحرية الجديدة",
    nameEn: "Jeddah New Waterfront",
    city: "جدة", cityEn: "Jeddah",
    category: "landmark", rating: 4.7, reviewCount: 15000, emoji: "⛵",
    image: "https://images.unsplash.com/photo-1512453979798-5ea266f8880c?w=800",
    descAr: "المشروع الطموح الذي يعيد رسم واجهة جدة البحرية بمرافق ترفيهية وسياحية متكاملة.",
    descEn: "The ambitious project redesigning Jeddah's waterfront with integrated tourism and entertainment facilities.",
  },
  {
    id: "a14",
    nameAr: "كايف أبها",
    nameEn: "Kaf Abha",
    city: "أبها", cityEn: "Abha",
    category: "entertainment", rating: 4.5, reviewCount: 6500, emoji: "🌄",
    image: "https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800",
    descAr: "مقصد سياحي جبلي فريد بأجواء ضبابية خلابة وطبيعة أسيرة في قلب عسير.",
    descEn: "A unique mountain tourist destination with breathtaking foggy atmospheres in the heart of Asir.",
  },
  {
    id: "a15",
    nameAr: "تروليات أبها",
    nameEn: "Abha Cable Cars",
    city: "أبها", cityEn: "Abha",
    category: "entertainment", rating: 4.6, reviewCount: 9200, emoji: "🚠",
    image: "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800",
    descAr: "أطول تلفريك سياحي في المملكة يمر فوق قمم جبال عسير بإطلالات رائعة.",
    descEn: "The longest tourist cable car in the Kingdom, passing over Asir mountain peaks with stunning views.",
  },
  {
    id: "a16",
    nameAr: "نخيل مول جدة",
    nameEn: "Nakheel Mall Jeddah",
    city: "جدة", cityEn: "Jeddah",
    category: "shopping", rating: 4.4, reviewCount: 21000, emoji: "🛍️",
    image: "https://images.unsplash.com/photo-1567449303183-ae0d6ed1498e?w=800",
    descAr: "من أكبر مراكز التسوق في جدة يحتضن أشهر العلامات التجارية العالمية.",
    descEn: "One of Jeddah's largest malls hosting the world's most renowned brands.",
  },
  {
    id: "a17",
    nameAr: "شاطئ العقير",
    nameEn: "Al-Uqayr Beach",
    city: "الأحساء", cityEn: "Al-Ahsa",
    category: "landmark", rating: 4.3, reviewCount: 4100, emoji: "🏖️",
    image: "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=800",
    descAr: "شاطئ رملي بكر على ساحل الخليج العربي قريب من واحة الأحساء التاريخية.",
    descEn: "A pristine sandy beach on the Arabian Gulf coast near the historic Al-Ahsa oasis.",
  },
  {
    id: "a18",
    nameAr: "واحة الأحساء",
    nameEn: "Al-Ahsa Oasis",
    city: "الأحساء", cityEn: "Al-Ahsa",
    category: "landmark", rating: 4.7, reviewCount: 8300, emoji: "🌴",
    image: "https://images.unsplash.com/photo-1518684079-3c830dcef090?w=800",
    descAr: "أكبر واحة نخيل في العالم وموقع تراث عالمي يونسكو في المنطقة الشرقية.",
    descEn: "The world's largest oasis and a UNESCO World Heritage Site in the Eastern Province.",
  },
  {
    id: "a19",
    nameAr: "بحيرة الأصفر",
    nameEn: "Al-Asfar Lake",
    city: "الأحساء", cityEn: "Al-Ahsa",
    category: "landmark", rating: 4.2, reviewCount: 3700, emoji: "💧",
    image: "https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?w=800",
    descAr: "بحيرة طبيعية نادرة في قلب الصحراء، تنتشر حولها الطيور المهاجرة في موسم الشتاء.",
    descEn: "A rare natural lake in the heart of the desert, surrounded by migratory birds in winter.",
  },
  {
    id: "a20",
    nameAr: "شارع العطارين — جدة القديمة",
    nameEn: "Al-Atarein Street — Old Jeddah",
    city: "جدة", cityEn: "Jeddah",
    category: "restaurant", rating: 4.4, reviewCount: 12000, emoji: "🍢",
    image: "https://images.unsplash.com/photo-1555396273-367ea4eb4db5?w=800",
    descAr: "شارع تراثي في قلب جدة التاريخية يعج بمطاعم الأكل الشعبي والحرف اليدوية.",
    descEn: "A heritage street in the heart of historic Jeddah bustling with local food and handicrafts.",
  },
  {
    id: "a21",
    nameAr: "برج المملكة",
    nameEn: "Kingdom Tower",
    city: "الرياض", cityEn: "Riyadh",
    category: "landmark", rating: 4.6, reviewCount: 19000, emoji: "🏙️",
    image: "https://images.unsplash.com/photo-1512453979798-5ea266f8880c?w=800",
    descAr: "الناطحة السماء الأيقونية في الرياض، تضم مركز تسوق فاخراً وجسراً زجاجياً بارتفاع 99 طابقاً.",
    descEn: "The iconic Riyadh skyscraper featuring a luxury mall and a glass sky bridge at 99 floors.",
  },
  {
    id: "a22",
    nameAr: "قلعة مدائن صالح",
    nameEn: "Madain Saleh Fortress",
    city: "العُلا", cityEn: "AlUla",
    category: "landmark", rating: 4.8, reviewCount: 6100, emoji: "🏯",
    image: "https://images.unsplash.com/photo-1591017403521-0d3c6e09f24e?w=800",
    descAr: "قلعة تاريخية تعود للحضارة النبطية بمناظر صخرية هائلة في صحراء الحجاز.",
    descEn: "A historic Nabataean fortress with massive rocky landscapes in the Hijaz desert.",
  },
  {
    id: "a23",
    nameAr: "فيلا روشن — جدة التاريخية",
    nameEn: "Villa Rowshan — Historic Jeddah",
    city: "جدة", cityEn: "Jeddah",
    category: "landmark", rating: 4.5, reviewCount: 7800, emoji: "🪟",
    image: "https://images.unsplash.com/photo-1578662996442-48f60103fc96?w=800",
    descAr: "إحدى درر العمارة الحجازية في جدة التاريخية المدرجة على قائمة التراث العالمي.",
    descEn: "One of the gems of Hijazi architecture in Historic Jeddah, a UNESCO World Heritage Site.",
  },
];

export const HOTEL_LISTINGS: HotelListing[] = [

  // ── الرياض — Riyadh ────────────────────────────────────────────────────────
  {
    id: "h1",
    nameAr: "فندق بوليفارد أربان ريزورت",
    nameEn: "Boulevard Urban Resort",
    city: "الرياض", cityEn: "Riyadh",
    district: "بوليفارد ورلد", districtEn: "Boulevard World",
    type: "hotel", stars: 5, pricePerNight: 1200,
    image: "https://images.unsplash.com/photo-1566073771259-6a8506099945?w=800",
    rating: 4.8, reviewCount: 2340, phone: "0112345678",
    amenitiesAr: ["واي فاي مجاني", "مسبح", "صالة رياضية", "سبا", "مطاعم متعددة", "خدمة غرف 24/7"],
    amenitiesEn: ["Free WiFi", "Pool", "Gym", "Spa", "Multiple Restaurants", "24/7 Room Service"],
    descAr: "أحد أفخم فنادق الرياض في قلب مشروع بوليفارد ورلد مع إطلالات رائعة وخدمات لا مثيل لها.",
    descEn: "One of Riyadh's most luxurious hotels in the heart of Boulevard World.",
    lat: 24.6973, lng: 46.6857,
  },
  {
    id: "h2",
    nameAr: "شقق ديرة الفاخرة - الدرعية",
    nameEn: "Dirah Luxury Suites - Diriyah",
    city: "الرياض", cityEn: "Riyadh",
    district: "الدرعية", districtEn: "Diriyah",
    type: "furnished_apt", stars: 4, pricePerNight: 550,
    image: "https://images.unsplash.com/photo-1595576508898-0ad5c879a061?w=800",
    rating: 4.6, reviewCount: 680, phone: "0114444444",
    amenitiesAr: ["قريب من الدرعية", "واي فاي فائق السرعة", "مطبخ فاخر", "بلكون", "خدمة تنظيف يومية"],
    amenitiesEn: ["Near Diriyah", "High-speed WiFi", "Luxury Kitchen", "Balcony", "Daily Housekeeping"],
    descAr: "شقق فاخرة بتصميم تراثي حديث خطوات من الدرعية التاريخية.",
    descEn: "Luxury apartments with contemporary heritage design steps from Diriyah.",
    lat: 24.7337, lng: 46.5716,
  },
  {
    id: "h3",
    nameAr: "فندق الريتز كارلتون الرياض",
    nameEn: "The Ritz-Carlton Riyadh",
    city: "الرياض", cityEn: "Riyadh",
    district: "حي العليا", districtEn: "Al-Olaya",
    type: "hotel", stars: 5, pricePerNight: 1800,
    image: "https://images.unsplash.com/photo-1571003123894-1f0594d2b5d9?w=800",
    rating: 4.9, reviewCount: 3800, phone: "0114777888",
    amenitiesAr: ["قصر فاخر", "حدائق شاسعة", "مسابح عدة", "سبا ملكي", "مطاعم عالمية"],
    amenitiesEn: ["Palatial Hotel", "Vast Gardens", "Multiple Pools", "Royal Spa", "World-class Dining"],
    descAr: "بناء مستوحى من العمارة النجدية التقليدية يوفر أرقى تجربة فندقية في قلب الرياض.",
    descEn: "A Najdi-inspired palace offering the finest hotel experience in the heart of Riyadh.",
    lat: 24.6930, lng: 46.7020,
  },
  {
    id: "h4",
    nameAr: "شقق النخيل السكنية - الرياض",
    nameEn: "Al-Nakhil Residential Suites - Riyadh",
    city: "الرياض", cityEn: "Riyadh",
    district: "النخيل", districtEn: "Al-Nakhil",
    type: "furnished_apt", stars: 3, pricePerNight: 320,
    image: "https://images.unsplash.com/photo-1522771739844-6a9f6d5f14af?w=800",
    rating: 4.3, reviewCount: 420, phone: "0114123456",
    amenitiesAr: ["واي فاي مجاني", "مطبخ مجهز", "موقف مجاني", "أمن 24 ساعة", "خدمة غسيل"],
    amenitiesEn: ["Free WiFi", "Equipped Kitchen", "Free Parking", "24h Security", "Laundry"],
    descAr: "شقق عائلية مريحة في حي النخيل بأسعار مناسبة للإقامة الطويلة.",
    descEn: "Comfortable family apartments in Al-Nakhil at affordable prices for long stays.",
    lat: 24.7780, lng: 46.7040,
  },
  {
    id: "h5",
    nameAr: "فندق فور سيزونز الرياض",
    nameEn: "Four Seasons Riyadh",
    city: "الرياض", cityEn: "Riyadh",
    district: "برج المملكة", districtEn: "Kingdom Tower",
    type: "hotel", stars: 5, pricePerNight: 2100,
    image: "https://images.unsplash.com/photo-1520250497591-112f2f40a3f4?w=800",
    rating: 4.9, reviewCount: 4100, phone: "0114888999",
    amenitiesAr: ["إطلالة بانورامية", "حمام سباحة علوي", "سبا فاخر", "مطاعم 5 نجوم", "خدمة شخصية"],
    amenitiesEn: ["Panoramic View", "Rooftop Pool", "Luxury Spa", "5-star Dining", "Personal Service"],
    descAr: "فندق فور سيزونز الأيقوني في قمة برج المملكة بإطلالة 360 درجة على الرياض.",
    descEn: "The iconic Four Seasons at the top of Kingdom Tower with 360° views of Riyadh.",
    lat: 24.6883, lng: 46.6838,
  },

  // ── جدة — Jeddah ─────────────────────────────────────────────────────────
  {
    id: "h6",
    nameAr: "شقق روزن المفروشة - جدة",
    nameEn: "Rozen Furnished Suites - Jeddah",
    city: "جدة", cityEn: "Jeddah",
    district: "حي الشاطئ", districtEn: "Al-Shati",
    type: "furnished_apt", stars: 4, pricePerNight: 480,
    image: "https://images.unsplash.com/photo-1522771739844-6a9f6d5f14af?w=800",
    rating: 4.6, reviewCount: 890, phone: "0121234567",
    amenitiesAr: ["واي فاي مجاني", "مطبخ مجهز", "غسيل ملابس", "موقف سيارات", "أمن 24 ساعة"],
    amenitiesEn: ["Free WiFi", "Equipped Kitchen", "Laundry", "Parking", "24h Security"],
    descAr: "شقق فاخرة مفروشة بالكامل على الكورنيش الشمالي بجدة، مثالية للعائلات.",
    descEn: "Fully furnished luxury apartments on Jeddah's North Corniche, ideal for families.",
    lat: 21.5433, lng: 39.1728,
  },
  {
    id: "h7",
    nameAr: "فندق هيلتون جدة",
    nameEn: "Hilton Jeddah",
    city: "جدة", cityEn: "Jeddah",
    district: "الكورنيش الشمالي", districtEn: "North Corniche",
    type: "hotel", stars: 5, pricePerNight: 1450,
    image: "https://images.unsplash.com/photo-1520250497591-112f2f40a3f4?w=800",
    rating: 4.7, reviewCount: 4200, phone: "0122222222",
    amenitiesAr: ["إطلالة البحر الأحمر", "مسبح", "سبا عالمي", "مطاعم دولية", "نادٍ صحي"],
    amenitiesEn: ["Red Sea View", "Pool", "World-class Spa", "International Dining", "Health Club"],
    descAr: "فندق هيلتون الأيقوني بإطلالات خلابة على البحر الأحمر.",
    descEn: "The iconic Hilton Jeddah with breathtaking Red Sea views.",
    lat: 21.5988, lng: 39.1041,
  },
  {
    id: "h8",
    nameAr: "منتجع شانغريلا جدة",
    nameEn: "Shangri-La Jeddah",
    city: "جدة", cityEn: "Jeddah",
    district: "الكورنيش", districtEn: "Corniche",
    type: "resort", stars: 5, pricePerNight: 1650,
    image: "https://images.unsplash.com/photo-1566073771259-6a8506099945?w=800",
    rating: 4.8, reviewCount: 2700, phone: "0126666777",
    amenitiesAr: ["شاطئ خاص", "منتجع مائي", "سبا شامل", "مطاعم آسيوية وعربية", "نادي أطفال"],
    amenitiesEn: ["Private Beach", "Water Park", "Full Spa", "Asian & Arab Dining", "Kids Club"],
    descAr: "منتجع فاخر على البحر الأحمر مباشرةً مع شاطئ خاص ومرافق لا مثيل لها.",
    descEn: "A luxury resort directly on the Red Sea with a private beach and unrivaled facilities.",
    lat: 21.5660, lng: 39.1050,
  },
  {
    id: "h9",
    nameAr: "شقق السامر المفروشة",
    nameEn: "Al-Samer Furnished Apartments",
    city: "جدة", cityEn: "Jeddah",
    district: "حي السامر", districtEn: "Al-Samer",
    type: "furnished_apt", stars: 3, pricePerNight: 280,
    image: "https://images.unsplash.com/photo-1596436889106-be35e843f974?w=800",
    rating: 4.2, reviewCount: 560, phone: "0125551234",
    amenitiesAr: ["واي فاي", "مطبخ", "تكييف مركزي", "مصعد", "حراسة"],
    amenitiesEn: ["WiFi", "Kitchen", "Central AC", "Elevator", "Security"],
    descAr: "شقق مريحة في حي السامر بجدة مناسبة للإقامة القصيرة والمتوسطة.",
    descEn: "Comfortable apartments in Al-Samer district, ideal for short and medium stays.",
    lat: 21.6250, lng: 39.1330,
  },
  {
    id: "h10",
    nameAr: "فندق رمادا جدة الجفالي",
    nameEn: "Ramada Jeddah Al-Jufali",
    city: "جدة", cityEn: "Jeddah",
    district: "الزهراء", districtEn: "Al-Zahra",
    type: "hotel", stars: 4, pricePerNight: 680,
    image: "https://images.unsplash.com/photo-1571003123894-1f0594d2b5d9?w=800",
    rating: 4.4, reviewCount: 1800, phone: "0126543210",
    amenitiesAr: ["مسبح", "واي فاي مجاني", "مطعم بوفيه", "صالة اجتماعات", "خدمة 24 ساعة"],
    amenitiesEn: ["Pool", "Free WiFi", "Buffet Restaurant", "Meeting Room", "24h Service"],
    descAr: "فندق راقٍ في حي الزهراء بجدة يجمع بين الراحة والموقع المثالي.",
    descEn: "An upscale hotel in Jeddah's Al-Zahra district combining comfort with prime location.",
    lat: 21.5820, lng: 39.1580,
  },

  // ── مكة المكرمة — Makkah ─────────────────────────────────────────────────
  {
    id: "h11",
    nameAr: "شقق زمرد للأجانب - مكة",
    nameEn: "Zomorrod Suites - Makkah",
    city: "مكة المكرمة", cityEn: "Makkah",
    district: "العزيزية", districtEn: "Al-Aziziyyah",
    type: "furnished_apt", stars: 4, pricePerNight: 650,
    image: "https://images.unsplash.com/photo-1631049307264-da0ec9d70304?w=800",
    rating: 4.7, reviewCount: 3400, phone: "0125555555",
    amenitiesAr: ["قريب من الحرم", "واي فاي مجاني", "خدمة عجلات كهربائية", "مطبخ متكامل"],
    amenitiesEn: ["Near Haram", "Free WiFi", "Electric Buggy Service", "Full Kitchen"],
    descAr: "شقق مريحة ومجهزة بالكامل على بُعد دقائق من المسجد الحرام.",
    descEn: "Comfortable fully-equipped apartments minutes from Al-Masjid Al-Haram.",
    lat: 21.3891, lng: 39.8579,
  },
  {
    id: "h12",
    nameAr: "برج ساعة مكة - فندق فيرمونت",
    nameEn: "Makkah Clock Tower - Fairmont",
    city: "مكة المكرمة", cityEn: "Makkah",
    district: "أجياد", districtEn: "Ajyad",
    type: "hotel", stars: 5, pricePerNight: 2800,
    image: "https://images.unsplash.com/photo-1566073771259-6a8506099945?w=800",
    rating: 4.9, reviewCount: 8900, phone: "0125888000",
    amenitiesAr: ["إطلالة مباشرة على الكعبة", "مسبح في الطابق الأعلى", "مطاعم فاخرة", "سبا", "نقل مجاني للحرم"],
    amenitiesEn: ["Direct Kaaba View", "Top-floor Pool", "Fine Dining", "Spa", "Free Haram Transfer"],
    descAr: "من أفخم فنادق العالم، يقع في برج الساعة الأيقوني بإطلالة مباشرة على الكعبة المشرفة.",
    descEn: "One of the world's most luxurious hotels in the iconic Clock Tower with a direct view of the Kaaba.",
    lat: 21.4197, lng: 39.8262,
  },
  {
    id: "h13",
    nameAr: "شقق المسفلة الماسية",
    nameEn: "Al-Misfalah Diamond Suites",
    city: "مكة المكرمة", cityEn: "Makkah",
    district: "المسفلة", districtEn: "Al-Misfalah",
    type: "furnished_apt", stars: 3, pricePerNight: 380,
    image: "https://images.unsplash.com/photo-1596436889106-be35e843f974?w=800",
    rating: 4.3, reviewCount: 2100, phone: "0125111222",
    amenitiesAr: ["قريب من الحرم", "واي فاي", "مطبخ", "تكييف", "موقف مدفوع"],
    amenitiesEn: ["Near Haram", "WiFi", "Kitchen", "AC", "Paid Parking"],
    descAr: "شقق بأسعار معقولة قريبة من باب المسفلة بالمسجد الحرام.",
    descEn: "Affordable apartments close to Bab Al-Misfalah at Al-Masjid Al-Haram.",
    lat: 21.4280, lng: 39.8480,
  },

  // ── المدينة المنورة — Madinah ────────────────────────────────────────────
  {
    id: "h14",
    nameAr: "شقق المدينة المنورة الذهبية",
    nameEn: "Madinah Gold Suites",
    city: "المدينة المنورة", cityEn: "Madinah",
    district: "قربان", districtEn: "Qurban",
    type: "furnished_apt", stars: 3, pricePerNight: 320,
    image: "https://images.unsplash.com/photo-1596436889106-be35e843f974?w=800",
    rating: 4.4, reviewCount: 2100, phone: "0148123456",
    amenitiesAr: ["قريب من المسجد النبوي", "واي فاي مجاني", "مطبخ", "تكييف", "موقف مجاني"],
    amenitiesEn: ["Near Prophet's Mosque", "Free WiFi", "Kitchen", "AC", "Free Parking"],
    descAr: "شقق مريحة وبأسعار مناسبة على بُعد دقيقتين من المسجد النبوي الشريف.",
    descEn: "Comfortable and affordable apartments just 2 minutes from the Prophet's Mosque.",
    lat: 24.4686, lng: 39.6142,
  },
  {
    id: "h15",
    nameAr: "فندق أنوار المدينة موفنبيك",
    nameEn: "Anwar Al Madinah Mövenpick",
    city: "المدينة المنورة", cityEn: "Madinah",
    district: "مركز المدينة", districtEn: "City Center",
    type: "hotel", stars: 5, pricePerNight: 950,
    image: "https://images.unsplash.com/photo-1571003123894-1f0594d2b5d9?w=800",
    rating: 4.8, reviewCount: 5600, phone: "0148999000",
    amenitiesAr: ["بوابة مباشرة للمسجد", "مطعم بوفيه عربي", "مسبح", "صالة رياضية", "خدمة صالون"],
    amenitiesEn: ["Direct Mosque Gate", "Arabic Buffet", "Pool", "Gym", "Salon Service"],
    descAr: "فندق خمس نجوم يشكّل بوابة مباشرة للمسجد النبوي مع كامل الخدمات الفاخرة.",
    descEn: "A 5-star hotel forming a direct gateway to the Prophet's Mosque with full luxury services.",
    lat: 24.4672, lng: 39.6101,
  },

  // ── العُلا — AlUla ──────────────────────────────────────────────────────
  {
    id: "h16",
    nameAr: "فندق العُلا الصحراوي",
    nameEn: "AlUla Desert Resort",
    city: "العُلا", cityEn: "AlUla",
    district: "قلب العُلا", districtEn: "AlUla Old Town",
    type: "resort", stars: 5, pricePerNight: 2200,
    image: "https://images.unsplash.com/photo-1587474260584-136574528ed5?w=800",
    rating: 4.9, reviewCount: 1120, phone: "0148888888",
    amenitiesAr: ["إطلالة الصحراء", "جولات أثرية", "مسبح لا نهائي", "مطعم فاخر", "نقل خاص"],
    amenitiesEn: ["Desert Views", "Archaeological Tours", "Infinity Pool", "Fine Dining", "Private Transfer"],
    descAr: "منتجع فاخر في قلب العُلا يوفر تجربة استثنائية في الصحراء العربية.",
    descEn: "A luxury resort in the heart of AlUla offering an extraordinary Arabian desert experience.",
    lat: 26.6358, lng: 37.9312,
  },
  {
    id: "h17",
    nameAr: "شانغريلا الحجر - العُلا",
    nameEn: "Banyan Tree AlUla",
    city: "العُلا", cityEn: "AlUla",
    district: "الحجر", districtEn: "Al-Hijr",
    type: "resort", stars: 5, pricePerNight: 3500,
    image: "https://images.unsplash.com/photo-1520250497591-112f2f40a3f4?w=800",
    rating: 4.9, reviewCount: 820, phone: "0148777666",
    amenitiesAr: ["خيام فاخرة", "جولات بالجمال", "مراقبة النجوم", "سبا صحراوي", "طبخ بدوي أصيل"],
    amenitiesEn: ["Luxury Tents", "Camel Tours", "Stargazing", "Desert Spa", "Authentic Bedouin Cooking"],
    descAr: "تجربة إقامة صحراوية لا تُنسى في خيام فاخرة تحت سماء العُلا المرصّعة بالنجوم.",
    descEn: "An unforgettable desert stay in luxury tents under AlUla's star-studded sky.",
    lat: 26.7900, lng: 37.9650,
  },

  // ── الدمام والخبر — Dammam & Khobar ─────────────────────────────────────
  {
    id: "h18",
    nameAr: "فندق كراون بلازا الدمام",
    nameEn: "Crowne Plaza Dammam",
    city: "الدمام", cityEn: "Dammam",
    district: "الشاطئ", districtEn: "Al-Shati",
    type: "hotel", stars: 5, pricePerNight: 850,
    image: "https://images.unsplash.com/photo-1571003123894-1f0594d2b5d9?w=800",
    rating: 4.5, reviewCount: 1780, phone: "0138887777",
    amenitiesAr: ["واجهة بحرية", "مسبح", "مركز أعمال", "مطعم دولي", "خدمة غرف 24/7"],
    amenitiesEn: ["Sea Front", "Pool", "Business Center", "International Restaurant", "24/7 Room Service"],
    descAr: "فندق راقٍ على كورنيش الدمام يوفر إطلالات رائعة على الخليج العربي.",
    descEn: "An upscale hotel on Dammam's corniche offering stunning Arabian Gulf views.",
    lat: 26.4207, lng: 50.1000,
  },
  {
    id: "h19",
    nameAr: "فندق ماريوت الخبر",
    nameEn: "Marriott Khobar",
    city: "الخبر", cityEn: "Khobar",
    district: "الكورنيش", districtEn: "Corniche",
    type: "hotel", stars: 5, pricePerNight: 980,
    image: "https://images.unsplash.com/photo-1566073771259-6a8506099945?w=800",
    rating: 4.7, reviewCount: 2900, phone: "0138001234",
    amenitiesAr: ["إطلالة الخليج", "مسبح خارجي", "مطعم دولي", "سبا", "قاعة أعمال كبرى"],
    amenitiesEn: ["Gulf View", "Outdoor Pool", "International Restaurant", "Spa", "Large Business Hall"],
    descAr: "فندق ماريوت الفاخر على كورنيش الخبر مع أرقى الخدمات وإطلالة الخليج العربي.",
    descEn: "The luxurious Marriott Khobar on the corniche with premium services and Arabian Gulf views.",
    lat: 26.2990, lng: 50.1980,
  },
  {
    id: "h20",
    nameAr: "شقق بيتش هاوس المفروشة - الخبر",
    nameEn: "Beach House Furnished Apts - Khobar",
    city: "الخبر", cityEn: "Khobar",
    district: "الأمواج", districtEn: "Amwaj",
    type: "furnished_apt", stars: 4, pricePerNight: 420,
    image: "https://images.unsplash.com/photo-1595576508898-0ad5c879a061?w=800",
    rating: 4.5, reviewCount: 740, phone: "0138112233",
    amenitiesAr: ["واجهة بحرية", "شرفة خاصة", "مطبخ كامل", "واي فاي", "موقف سيارات"],
    amenitiesEn: ["Seafront", "Private Balcony", "Full Kitchen", "WiFi", "Parking"],
    descAr: "شقق مطلة على البحر في مجمع الأمواج بالخبر، مثالية للعائلات.",
    descEn: "Sea-view apartments in Khobar's Amwaj complex, perfect for families.",
    lat: 26.2720, lng: 50.2120,
  },

  // ── أبها وعسير — Abha & Asir ─────────────────────────────────────────────
  {
    id: "h21",
    nameAr: "منتجع جبال عسير",
    nameEn: "Asir Mountains Resort",
    city: "أبها", cityEn: "Abha",
    district: "الشفا", districtEn: "Al-Shafa",
    type: "resort", stars: 5, pricePerNight: 1100,
    image: "https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800",
    rating: 4.8, reviewCount: 1450, phone: "0172201234",
    amenitiesAr: ["إطلالة الجبال", "تلفريك", "مسبح جبلي", "مطعم صحي", "أنشطة في الهواء الطلق"],
    amenitiesEn: ["Mountain Views", "Cable Car", "Mountain Pool", "Health Restaurant", "Outdoor Activities"],
    descAr: "منتجع استثنائي في جبال عسير بأجواء معتدلة طوال العام وإطلالات خلابة.",
    descEn: "An extraordinary resort in the Asir mountains with year-round mild weather and stunning views.",
    lat: 18.1800, lng: 42.4780,
  },
  {
    id: "h22",
    nameAr: "شقق الضباب الجبلية - أبها",
    nameEn: "Al-Dabab Mountain Suites - Abha",
    city: "أبها", cityEn: "Abha",
    district: "الوسام", districtEn: "Al-Wisam",
    type: "furnished_apt", stars: 3, pricePerNight: 250,
    image: "https://images.unsplash.com/photo-1596436889106-be35e843f974?w=800",
    rating: 4.4, reviewCount: 890, phone: "0172301122",
    amenitiesAr: ["إطلالة ضبابية", "واي فاي", "مطبخ", "تدفئة مركزية", "حديقة"],
    amenitiesEn: ["Misty Views", "WiFi", "Kitchen", "Central Heating", "Garden"],
    descAr: "شقق جبلية هادئة في قلب أبها بأجواء باردة ومنعشة مع إطلالات ضبابية رائعة.",
    descEn: "Quiet mountain apartments in the heart of Abha with cool refreshing atmosphere.",
    lat: 18.2164, lng: 42.5053,
  },

  // ── تبوك — Tabuk ──────────────────────────────────────────────────────────
  {
    id: "h23",
    nameAr: "منتجع شرما البحري - تبوك",
    nameEn: "Sharma Marine Resort - Tabuk",
    city: "تبوك", cityEn: "Tabuk",
    district: "شرما", districtEn: "Sharma",
    type: "resort", stars: 5, pricePerNight: 1900,
    image: "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=800",
    rating: 4.8, reviewCount: 620, phone: "0144001122",
    amenitiesAr: ["شعاب مرجانية", "غوص", "شاطئ خاص", "مطعم مأكولات بحرية", "قوارب خاصة"],
    amenitiesEn: ["Coral Reefs", "Diving", "Private Beach", "Seafood Restaurant", "Private Boats"],
    descAr: "منتجع حصري على خليج العقبة بشعاب مرجانية بكر ومياه زرقاء فيروزية.",
    descEn: "An exclusive resort on the Gulf of Aqaba with pristine coral reefs and turquoise waters.",
    lat: 28.0500, lng: 35.2000,
  },
  {
    id: "h24",
    nameAr: "فندق تبوك بارك",
    nameEn: "Tabuk Park Hotel",
    city: "تبوك", cityEn: "Tabuk",
    district: "الروابي", districtEn: "Al-Rawabi",
    type: "hotel", stars: 4, pricePerNight: 520,
    image: "https://images.unsplash.com/photo-1595576508898-0ad5c879a061?w=800",
    rating: 4.3, reviewCount: 780, phone: "0144112233",
    amenitiesAr: ["مسبح", "واي فاي مجاني", "مطعم", "صالة رياضية", "موقف مجاني"],
    amenitiesEn: ["Pool", "Free WiFi", "Restaurant", "Gym", "Free Parking"],
    descAr: "فندق مريح في قلب تبوك يوفر جميع الخدمات الأساسية بموقع مركزي.",
    descEn: "A comfortable hotel in the heart of Tabuk providing all essential services in a central location.",
    lat: 28.3992, lng: 36.5662,
  },

  // ── الأحساء — Al-Ahsa ────────────────────────────────────────────────────
  {
    id: "h25",
    nameAr: "فندق واحة الأحساء",
    nameEn: "Al-Ahsa Oasis Hotel",
    city: "الأحساء", cityEn: "Al-Ahsa",
    district: "الهفوف", districtEn: "Al-Hofuf",
    type: "hotel", stars: 4, pricePerNight: 450,
    image: "https://images.unsplash.com/photo-1571003123894-1f0594d2b5d9?w=800",
    rating: 4.4, reviewCount: 960, phone: "0135001234",
    amenitiesAr: ["حديقة نخيل", "مسبح", "واي فاي", "مطعم خليجي", "جولات الواحة"],
    amenitiesEn: ["Palm Garden", "Pool", "WiFi", "Gulf Restaurant", "Oasis Tours"],
    descAr: "فندق فريد في قلب واحة الأحساء يتيح لك استكشاف أكبر واحة نخيل في العالم.",
    descEn: "A unique hotel in the heart of Al-Ahsa Oasis, letting you explore the world's largest palm oasis.",
    lat: 25.3800, lng: 49.5900,
  },
];

export const TOURISM_CITIES = [
  { nameAr: "الرياض",         nameEn: "Riyadh",   emoji: "🏙️" },
  { nameAr: "جدة",            nameEn: "Jeddah",   emoji: "🌊" },
  { nameAr: "مكة المكرمة",    nameEn: "Makkah",   emoji: "🕋" },
  { nameAr: "المدينة المنورة", nameEn: "Madinah",  emoji: "🕌" },
  { nameAr: "العُلا",         nameEn: "AlUla",    emoji: "🗿" },
  { nameAr: "الدمام",         nameEn: "Dammam",   emoji: "⛽" },
  { nameAr: "أبها",           nameEn: "Abha",     emoji: "🌄" },
  { nameAr: "تبوك",           nameEn: "Tabuk",    emoji: "🏔️" },
];
