// ─────────────────────────────────────────────────────────────────────────────
// Mock tourism data — Saudi attractions + hotels/furnished apartments
// ─────────────────────────────────────────────────────────────────────────────

export type AttractionCategory = "landmark" | "entertainment" | "restaurant" | "shopping";

export interface Attraction {
  id: string;
  nameAr: string;
  nameEn: string;
  city: string;
  cityEn: string;
  category: AttractionCategory;
  rating: number;
  reviewCount: number;
  emoji: string;
  descAr: string;
  descEn: string;
  image: string;
}

export interface HotelListing {
  id: string;
  nameAr: string;
  nameEn: string;
  city: string;
  cityEn: string;
  district: string;
  districtEn: string;
  type: "hotel" | "furnished_apt";
  stars: number;
  pricePerNight: number;
  image: string;
  rating: number;
  reviewCount: number;
  phone: string;
  amenitiesAr: string[];
  amenitiesEn: string[];
  descAr: string;
  descEn: string;
  lat: number;
  lng: number;
}

export const ATTRACTIONS: Attraction[] = [
  {
    id: "a1",
    nameAr: "الدرعية التاريخية",
    nameEn: "Historic Diriyah",
    city: "الرياض",
    cityEn: "Riyadh",
    category: "landmark",
    rating: 4.9,
    reviewCount: 12500,
    emoji: "🏛️",
    image: "https://images.unsplash.com/photo-1578662996442-48f60103fc96?w=800",
    descAr: "مدينة الدرعية التاريخية، مهد الدولة السعودية الأولى وأحد أبرز المواقع التراثية في العالم. تضم قصور الطين الأصيلة ومتاحف تحكي تاريخ المملكة.",
    descEn: "The Historic Diriyah is the birthplace of the first Saudi state and one of the world's most prominent heritage sites, featuring authentic mud palaces and museums.",
  },
  {
    id: "a2",
    nameAr: "العُلا",
    nameEn: "AlUla",
    city: "العُلا",
    cityEn: "AlUla",
    category: "landmark",
    rating: 4.9,
    reviewCount: 8900,
    emoji: "🗿",
    image: "https://images.unsplash.com/photo-1591017403521-0d3c6e09f24e?w=800",
    descAr: "وجهة سياحية استثنائية تضم أقدم المواقع الأثرية في شبه الجزيرة العربية، بما فيها الحِجر ومناظر الجبال الخلابة.",
    descEn: "An exceptional destination featuring some of the Arabian Peninsula's oldest archaeological sites, including Hegra and breathtaking mountain landscapes.",
  },
  {
    id: "a3",
    nameAr: "بوليفارد الرياض",
    nameEn: "Boulevard Riyadh",
    city: "الرياض",
    cityEn: "Riyadh",
    category: "entertainment",
    rating: 4.7,
    reviewCount: 34000,
    emoji: "🎡",
    image: "https://images.unsplash.com/photo-1514890547357-a9ee288728e0?w=800",
    descAr: "مدينة ترفيهية متكاملة تضم أكثر من 100 وجهة ترفيهية وتجارية وفعاليات يومية متنوعة.",
    descEn: "A full-scale entertainment city with over 100 dining, retail, and entertainment destinations plus daily events.",
  },
  {
    id: "a4",
    nameAr: "كورنيش جدة",
    nameEn: "Jeddah Corniche",
    city: "جدة",
    cityEn: "Jeddah",
    category: "landmark",
    rating: 4.6,
    reviewCount: 22000,
    emoji: "🌊",
    image: "https://images.unsplash.com/photo-1565541962553-5c1dae0d5e83?w=800",
    descAr: "واجهة بحرية ممتدة على 30 كيلومتراً تطل على البحر الأحمر، مثالية للنزهات والمشي.",
    descEn: "A 30-kilometer seafront promenade along the Red Sea, perfect for walks and leisure.",
  },
  {
    id: "a5",
    nameAr: "نيوم",
    nameEn: "NEOM",
    city: "تبوك",
    cityEn: "Tabuk",
    category: "landmark",
    rating: 4.8,
    reviewCount: 5200,
    emoji: "🌆",
    image: "https://images.unsplash.com/photo-1486325212027-8081e485255e?w=800",
    descAr: "مدينة المستقبل على ساحل البحر الأحمر، مشروع رؤية 2030 الطموح.",
    descEn: "The city of the future on the Red Sea coast, Saudi Vision 2030's ambitious megaproject.",
  },
  {
    id: "a6",
    nameAr: "قرية الحجاز",
    nameEn: "Al-Hijaz Village",
    city: "جدة",
    cityEn: "Jeddah",
    category: "restaurant",
    rating: 4.5,
    reviewCount: 9800,
    emoji: "🍽️",
    image: "https://images.unsplash.com/photo-1555396273-367ea4eb4db5?w=800",
    descAr: "قرية تراثية تجمع أشهى المطاعم الحجازية الأصيلة في أجواء تراثية فريدة.",
    descEn: "A heritage village gathering the finest authentic Hijazi restaurants in a unique traditional setting.",
  },
  {
    id: "a7",
    nameAr: "مول الرياض",
    nameEn: "Riyadh Mall",
    city: "الرياض",
    cityEn: "Riyadh",
    category: "shopping",
    rating: 4.3,
    reviewCount: 18000,
    emoji: "🛍️",
    image: "https://images.unsplash.com/photo-1567449303183-ae0d6ed1498e?w=800",
    descAr: "أحد أبرز مراكز التسوق في الرياض مع أكثر من 400 متجر وخيارات ترفيه متعددة.",
    descEn: "One of Riyadh's premier shopping destinations with over 400 stores and multiple entertainment options.",
  },
  {
    id: "a8",
    nameAr: "حديقة الملك فهد",
    nameEn: "King Fahd Park",
    city: "الدمام",
    cityEn: "Dammam",
    category: "entertainment",
    rating: 4.4,
    reviewCount: 7600,
    emoji: "🌳",
    image: "https://images.unsplash.com/photo-1441974231531-c6227db76b6e?w=800",
    descAr: "أكبر حديقة عامة في المنطقة الشرقية مع مناطق ألعاب ومسارات للمشي وأنشطة عائلية.",
    descEn: "The largest public park in the Eastern Province with playgrounds, walking trails, and family activities.",
  },
  {
    id: "a9",
    nameAr: "المسجد الحرام",
    nameEn: "Al-Masjid Al-Haram",
    city: "مكة المكرمة",
    cityEn: "Makkah",
    category: "landmark",
    rating: 5.0,
    reviewCount: 150000,
    emoji: "🕋",
    image: "https://images.unsplash.com/photo-1565534887628-fc54cdf7bf3d?w=800",
    descAr: "المسجد الحرام بمكة المكرمة، أقدس مكان في الإسلام ومقصد ملايين المسلمين.",
    descEn: "Al-Masjid Al-Haram in Makkah, the holiest site in Islam and destination of millions of pilgrims.",
  },
  {
    id: "a10",
    nameAr: "المسجد النبوي",
    nameEn: "Al-Masjid An-Nabawi",
    city: "المدينة المنورة",
    cityEn: "Madinah",
    category: "landmark",
    rating: 5.0,
    reviewCount: 120000,
    emoji: "🕌",
    image: "https://images.unsplash.com/photo-1591604129939-f1efa4d9f7fa?w=800",
    descAr: "المسجد النبوي الشريف في المدينة المنورة، ثاني أقدس المساجد في الإسلام.",
    descEn: "The Prophet's Mosque in Madinah, the second holiest mosque in Islam.",
  },
  {
    id: "a11",
    nameAr: "نادي الرياض الترفيهي",
    nameEn: "Riyadh Season",
    city: "الرياض",
    cityEn: "Riyadh",
    category: "entertainment",
    rating: 4.6,
    reviewCount: 28000,
    emoji: "🎭",
    image: "https://images.unsplash.com/photo-1492684223066-81342ee5ff30?w=800",
    descAr: "موسم الرياض، أكبر حدث ترفيهي في المملكة يجمع أشهر الفنانين والعروض العالمية.",
    descEn: "Riyadh Season, the Kingdom's largest entertainment event featuring world-class artists and shows.",
  },
  {
    id: "a12",
    nameAr: "متحف المملكة",
    nameEn: "Museum of the Kingdom",
    city: "الرياض",
    cityEn: "Riyadh",
    category: "landmark",
    rating: 4.5,
    reviewCount: 11000,
    emoji: "🏛️",
    image: "https://images.unsplash.com/photo-1566127992631-137a642a90f4?w=800",
    descAr: "متحف يوثّق تاريخ المملكة العربية السعودية من العصور الحجرية حتى اليوم.",
    descEn: "A museum documenting Saudi Arabia's history from the Stone Age to the present.",
  },
];

export const HOTEL_LISTINGS: HotelListing[] = [
  {
    id: "h1",
    nameAr: "فندق بوليفارد أربان ريزورت",
    nameEn: "Boulevard Urban Resort",
    city: "الرياض",
    cityEn: "Riyadh",
    district: "بوليفارد ورلد",
    districtEn: "Boulevard World",
    type: "hotel",
    stars: 5,
    pricePerNight: 1200,
    image: "https://images.unsplash.com/photo-1566073771259-6a8506099945?w=800",
    rating: 4.8,
    reviewCount: 2340,
    phone: "0112345678",
    amenitiesAr: ["واي فاي مجاني", "مسبح", "صالة رياضية", "سبا", "مطاعم متعددة", "خدمة غرف 24/7"],
    amenitiesEn: ["Free WiFi", "Pool", "Gym", "Spa", "Multiple Restaurants", "24/7 Room Service"],
    descAr: "أحد أفخم فنادق الرياض، يقع في قلب مشروع بوليفارد ورلد مع إطلالات رائعة وخدمات لا مثيل لها.",
    descEn: "One of Riyadh's most luxurious hotels, located in the heart of Boulevard World with stunning views and world-class services.",
    lat: 24.6973,
    lng: 46.6857,
  },
  {
    id: "h2",
    nameAr: "شقق روزن المفروشة - جدة",
    nameEn: "Rozen Furnished Suites - Jeddah",
    city: "جدة",
    cityEn: "Jeddah",
    district: "حي الشاطئ",
    districtEn: "Al-Shati District",
    type: "furnished_apt",
    stars: 4,
    pricePerNight: 480,
    image: "https://images.unsplash.com/photo-1522771739844-6a9f6d5f14af?w=800",
    rating: 4.6,
    reviewCount: 890,
    phone: "0121234567",
    amenitiesAr: ["واي فاي مجاني", "مطبخ مجهز", "غسيل ملابس", "موقف سيارات", "أمن 24 ساعة"],
    amenitiesEn: ["Free WiFi", "Equipped Kitchen", "Laundry", "Parking", "24h Security"],
    descAr: "شقق فاخرة مفروشة بالكامل على الكورنيش الشمالي بجدة، مثالية للعائلات والإقامات الطويلة.",
    descEn: "Fully furnished luxury apartments on Jeddah's North Corniche, ideal for families and extended stays.",
    lat: 21.5433,
    lng: 39.1728,
  },
  {
    id: "h3",
    nameAr: "فندق العُلا الصحراوي",
    nameEn: "AlUla Desert Resort",
    city: "العُلا",
    cityEn: "AlUla",
    district: "قلب العُلا",
    districtEn: "AlUla Old Town",
    type: "hotel",
    stars: 5,
    pricePerNight: 2200,
    image: "https://images.unsplash.com/photo-1587474260584-136574528ed5?w=800",
    rating: 4.9,
    reviewCount: 1120,
    phone: "0148888888",
    amenitiesAr: ["إطلالة الصحراء", "جولات أثرية", "مسبح لا نهائي", "مطعم فاخر", "نقل خاص"],
    amenitiesEn: ["Desert Views", "Archaeological Tours", "Infinity Pool", "Fine Dining", "Private Transfer"],
    descAr: "منتجع فاخر في قلب العُلا يوفر تجربة استثنائية في الصحراء العربية مع قُرب من المواقع الأثرية.",
    descEn: "A luxury resort in the heart of AlUla offering an extraordinary Arabian desert experience near archaeological sites.",
    lat: 26.6358,
    lng: 37.9312,
  },
  {
    id: "h4",
    nameAr: "شقق زمرد للأجانب - مكة",
    nameEn: "Zomorrod Suites - Makkah",
    city: "مكة المكرمة",
    cityEn: "Makkah",
    district: "العزيزية",
    districtEn: "Al-Aziziyyah",
    type: "furnished_apt",
    stars: 4,
    pricePerNight: 650,
    image: "https://images.unsplash.com/photo-1631049307264-da0ec9d70304?w=800",
    rating: 4.7,
    reviewCount: 3400,
    phone: "0125555555",
    amenitiesAr: ["قريب من الحرم", "واي فاي مجاني", "خدمة عجلات كهربائية", "مطبخ متكامل", "تكييف مركزي"],
    amenitiesEn: ["Near Haram", "Free WiFi", "Electric Buggy Service", "Full Kitchen", "Central AC"],
    descAr: "شقق مريحة ومجهزة بالكامل على بُعد دقائق من المسجد الحرام، مثالية لزوار موسم الحج والعمرة.",
    descEn: "Comfortable fully-equipped apartments minutes from Al-Masjid Al-Haram, ideal for Hajj and Umrah visitors.",
    lat: 21.3891,
    lng: 39.8579,
  },
  {
    id: "h5",
    nameAr: "فندق كراون بلازا الدمام",
    nameEn: "Crowne Plaza Dammam",
    city: "الدمام",
    cityEn: "Dammam",
    district: "الشاطئ",
    districtEn: "Al-Shati",
    type: "hotel",
    stars: 5,
    pricePerNight: 850,
    image: "https://images.unsplash.com/photo-1571003123894-1f0594d2b5d9?w=800",
    rating: 4.5,
    reviewCount: 1780,
    phone: "0138887777",
    amenitiesAr: ["واجهة بحرية", "مسبح", "مركز أعمال", "مطعم دولي", "خدمة غرف 24/7"],
    amenitiesEn: ["Sea Front", "Pool", "Business Center", "International Restaurant", "24/7 Room Service"],
    descAr: "فندق راقٍ على كورنيش الدمام يوفر إطلالات رائعة على الخليج العربي وخدمات متكاملة.",
    descEn: "An upscale hotel on Dammam's corniche offering stunning Arabian Gulf views and comprehensive services.",
    lat: 26.4207,
    lng: 50.1000,
  },
  {
    id: "h6",
    nameAr: "شقق المدينة المنورة الذهبية",
    nameEn: "Madinah Gold Suites",
    city: "المدينة المنورة",
    cityEn: "Madinah",
    district: "قربان",
    districtEn: "Qurban",
    type: "furnished_apt",
    stars: 3,
    pricePerNight: 320,
    image: "https://images.unsplash.com/photo-1596436889106-be35e843f974?w=800",
    rating: 4.4,
    reviewCount: 2100,
    phone: "0148123456",
    amenitiesAr: ["قريب من المسجد النبوي", "واي فاي مجاني", "مطبخ", "تكييف", "موقف مجاني"],
    amenitiesEn: ["Near Prophet's Mosque", "Free WiFi", "Kitchen", "AC", "Free Parking"],
    descAr: "شقق مريحة وبأسعار مناسبة على بُعد دقيقتين من المسجد النبوي الشريف.",
    descEn: "Comfortable and affordable apartments just 2 minutes from the Prophet's Mosque.",
    lat: 24.4686,
    lng: 39.6142,
  },
  {
    id: "h7",
    nameAr: "فندق هيلتون جدة",
    nameEn: "Hilton Jeddah",
    city: "جدة",
    cityEn: "Jeddah",
    district: "الكورنيش الشمالي",
    districtEn: "North Corniche",
    type: "hotel",
    stars: 5,
    pricePerNight: 1450,
    image: "https://images.unsplash.com/photo-1520250497591-112f2f40a3f4?w=800",
    rating: 4.7,
    reviewCount: 4200,
    phone: "0122222222",
    amenitiesAr: ["إطلالة البحر الأحمر", "مسبح", "سبا عالمي", "مطاعم دولية", "نادٍ صحي"],
    amenitiesEn: ["Red Sea View", "Pool", "World-class Spa", "International Dining", "Health Club"],
    descAr: "فندق هيلتون الأيقوني بإطلالات خلابة على البحر الأحمر وأعلى مستويات الضيافة.",
    descEn: "The iconic Hilton Jeddah with breathtaking Red Sea views and the highest standards of hospitality.",
    lat: 21.5988,
    lng: 39.1041,
  },
  {
    id: "h8",
    nameAr: "شقق ديرة الفاخرة - الرياض",
    nameEn: "Dirah Luxury Suites - Riyadh",
    city: "الرياض",
    cityEn: "Riyadh",
    district: "الدرعية",
    districtEn: "Diriyah",
    type: "furnished_apt",
    stars: 4,
    pricePerNight: 550,
    image: "https://images.unsplash.com/photo-1595576508898-0ad5c879a061?w=800",
    rating: 4.6,
    reviewCount: 680,
    phone: "0114444444",
    amenitiesAr: ["قريب من الدرعية", "واي فاي فائق السرعة", "مطبخ فاخر", "بلكون", "خدمة تنظيف يومية"],
    amenitiesEn: ["Near Diriyah", "High-speed WiFi", "Luxury Kitchen", "Balcony", "Daily Housekeeping"],
    descAr: "شقق فاخرة بتصميم تراثي حديث تجمع بين الأصالة والمعاصرة على بُعد خطوات من الدرعية.",
    descEn: "Luxury apartments with contemporary heritage design, blending tradition and modernity steps from Diriyah.",
    lat: 24.7337,
    lng: 46.5716,
  },
];

export const TOURISM_CITIES = [
  { nameAr: "الرياض",        nameEn: "Riyadh",  emoji: "🏙️" },
  { nameAr: "جدة",           nameEn: "Jeddah",  emoji: "🌊" },
  { nameAr: "مكة المكرمة",   nameEn: "Makkah",  emoji: "🕋" },
  { nameAr: "المدينة المنورة",nameEn: "Madinah", emoji: "🕌" },
  { nameAr: "العُلا",        nameEn: "AlUla",   emoji: "🗿" },
  { nameAr: "الدمام",        nameEn: "Dammam",  emoji: "⛽" },
];
