kind = "mobile"
previewPath = "/oprox-properties/"
title = "OPROX Properties"
version = "1.0.0"
id = "artifacts/rkz"
router = "expo-domain"

[[integratedSkills]]
name = "expo"
version = "1.0.0"

[[services]]
ensurePreviewReachable = "/status"
name = "OPROX Properties"
paths = [ "/oprox-properties/", "/oprox-properties" ]
localPort = 26232

[services.development]
run = "pnpm --filter @workspace/oprox-properties run dev"

[services.production]
build = [ "pnpm", "--filter", "@workspace/oprox-properties", "run", "build" ]
run = [ "pnpm", "--filter", "@workspace/oprox-properties", "run", "serve" ]

[services.env]
PORT = "26232"
BASE_PATH = "/oprox-properties/"
