kind = "mobile"
previewPath = "/rozoz-msrep/"
title = "Rozoz"
version = "1.0.0"
id = "artifacts/rkz"
router = "expo-domain"

[[integratedSkills]]
name = "expo"
version = "1.0.0"

[[services]]
ensurePreviewReachable = "/status"
name = "expo"
paths = [ "/rozoz-msrep/", "/rozoz-msrep" ]
localPort = 26232

[services.development]
run = "pnpm --filter @workspace/rozoz-msrep run dev"

[services.production]
build = [ "pnpm", "--filter", "@workspace/rozoz-msrep", "run", "build" ]
run = [ "pnpm", "--filter", "@workspace/rozoz-msrep", "run", "serve" ]

[services.env]
PORT = "26232"
BASE_PATH = "/rozoz-msrep/"
