import type { Translations } from "./en";

const ml: Translations = {
  nav: { units: "യൂണിറ്റുകൾ", workOrders: "വർക്ക് ഓർഡറുകൾ", tasks: "എൻ്റെ ജോലികൾ" },
  status: { available: "ലഭ്യം", occupied: "ഉപയോഗത്തിൽ", maintenance: "അറ്റകുറ്റപ്പണി", cleaning: "ശുചീകരണം", pending: "തീർപ്പാക്കാത്തത്", inProgress: "പ്രക്രിയയിൽ", completed: "പൂർത്തിയായി", cancelled: "റദ്ദാക്കി", verified: "സ്ഥിരീകരിച്ചു" },
  priority: { urgent: "അടിയന്തിര", high: "ഉയർന്ന", medium: "ഇടത്തരം", low: "കുറഞ്ഞ" },
  dashboard: { appSubtitle: "സ്റ്റാഫ് ഡാഷ്‌ബോർഡ്", totalUnits: "മൊത്തം യൂണിറ്റുകൾ", allProperties: "എല്ലാ പ്രോപ്പർട്ടികളും", logout: "ലോഗ് ഔട്ട്" },
  workOrders: { title: "വർക്ക് ഓർഡറുകൾ", subtitle: "എൻ്റെ വർക്ക് ഓർഡറുകൾ", pending: "തീർപ്പാക്കാത്തത്", inProgress: "പ്രക്രിയയിൽ", done: "പൂർത്തി", all: "എല്ലാം", startWork: "ജോലി ആരംഭിക്കുക", complete: "പൂർത്തിയാക്കുക", completedDone: "പൂർത്തിയായി", empty: "വർക്ക് ഓർഡറുകൾ ഇല്ല", emptyDesc: "ജോലി ഒന്നും നിശ്ചയിക്കപ്പെട്ടിട്ടില്ല", failedLoad: "ലോഡ് ചെയ്യുന്നതിൽ പരാജയം", retry: "വീണ്ടും ശ്രമിക്കുക", toastStarted: "ആരംഭിച്ചു", toastCompleted: "പൂർത്തിയായി", toastFailed: "അപ്‌ഡേറ്റ് പരാജയം" },
  tasks: { title: "എൻ്റെ നിലവിലെ ജോലികൾ", pending: "തീർപ്പാക്കാത്തത്", active: "സജീവം", done: "പൂർത്തി", startTask: "ജോലി ആരംഭിക്കുക", endTask: "ജോലി അവസാനിപ്പിക്കുക", awaitingApproval: "അനുമതിക്കായി കാത്തിരിക്കുന്നു", completedAwaiting: "പൂർത്തിയായി — അനുമതിക്കായി കാത്തിരിക്കുന്നു", approved: "അനുമതി ലഭിച്ചു", completeTask: "ജോലി പൂർത്തിയാക്കുക", taskLabel: "ജോലി", completionPhoto: "പൂർത്തിയാക്കൽ ഫോട്ടോ", tapPhoto: "ഫോട്ടോ എടുക്കാൻ ടാപ്പ് ചെയ്യുക", gpsLocation: "GPS ലൊക്കേഷൻ", locationGetting: "നിങ്ങളുടെ ലൊക്കേഷൻ ലഭിക്കുന്നു...", locationDone: "ലൊക്കേഷൻ രേഖപ്പെടുത്തി", locationFailed: "ലൊക്കേഷൻ ലഭിക്കുന്നതിൽ പരാജയം", allowLocation: "ബ്രൗസർ ക്രമീകരണങ്ങളിൽ ലൊക്കേഷൻ അനുവദിക്കുക", retryGps: "വീണ്ടും ശ്രമിക്കുക", requirements: "ആവശ്യകതകൾ", photo: "ഫോട്ടോ", submitReport: "റിപ്പോർട്ട് സമർപ്പിക്കുക", submitting: "സമർപ്പിക്കുന്നു...", cancel: "റദ്ദാക്കുക" },
  unitDetail: { unitStatus: "യൂണിറ്റ് സ്ഥിതി", financialData: "സാമ്പത്തിക ഡാറ്റ", serviceRequests: "സേവന അഭ്യർത്ഥനകൾ", setStatus: "സ്ഥിതി സജ്ജമാക്കുക", type: "തരം", capacity: "ശേഷി", rate: "നിരക്ക്", status: "സ്ഥിതി", amountDue: "കുടിശ്ശിക തുക", dueDate: "അവസാന തീയതി", checkIn: "ചെക്ക്-ഇൻ", checkOut: "ചെക്ക്-ഔട്ട്", saveChanges: "മാറ്റങ്ങൾ സംരക്ഷിക്കുക", noFinancial: "സാമ്പത്തിക ഡാറ്റ ഇല്ല", addFinancial: "സാമ്പത്തിക ഡാറ്റ ചേർക്കുക", noRequests: "ഈ യൂണിറ്റിനായി അഭ്യർത്ഥനകൾ ഇല്ല", resolve: "പരിഹരിക്കുക", qrTitle: "സേവന അഭ്യർത്ഥന QR", copyLink: "ലിങ്ക് പകർത്തുക", copied: "ലിങ്ക് പകർത്തി!", guests: "അതിഥികൾ", perNight: "/രാത്രി", loading: "ലോഡ് ആകുന്നു…", edit: "എഡിറ്റ്", cancel: "റദ്ദാക്കുക", new: "പുതിയത്", offline: "ഓഫ്‌ലൈൻ — കണക്‌റ്റ് ആകുമ്പോൾ സിങ്ക് ആകും" },
  lang: { select: "ഭാഷ" },
};

export default ml;
